using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ExerciseCuration.Core
{
    public class Exercise
    {
        private readonly List<exerciseSnippet> exercises =new List<exerciseSnippet>()
        {
            new exerciseSnippet("Star Jump", "Start standing with your feet together and your knees slightly bent. Your arms should be bent up in front of your chest, like you’re carrying firewood. Next, step your legs out quickly, one leg at a time and shoot your arms out diagonally so you create a star.", 1, 1, goal.LoseWeight, workoutTypes.WeightLoss, difficulty.beginner),
            new exerciseSnippet("Fast Feet Touchdown", "Stand with your feet a little wider than hip-width apart. Bend your knees and turn out your feet slightly. Loosely hold your arms bent in front of your chest. Balance your weight on the balls of your feet. Keep your upper body relatively stable and focus on moving your feet as fast as you can. Once you step five times on each foot, quickly bend down, touch the ground, and then rise back up and continue hot-stepping from foot to foot. Repeat for 60 seconds.", 1, 1, goal.LoseWeight, workoutTypes.WeightLoss, difficulty.beginner),
            new exerciseSnippet("Single-Leg Skip", "Stand with the right leg behind you in a shallow lunge position. As if you’re about to run a sprint, bend your arms and bring the right arm in front of you, left arm behind you. Push off your back foot and perform a skip on your left leg, bringing your right leg up and driving up with your left arm. Land softly on our left leg and bring your right leg back to the starting sprint position. Perform 10 reps on each side.", 10, 1, goal.LoseWeight, workoutTypes.WeightLoss, difficulty.beginner),
            new exerciseSnippet("Overhead Chop", "Start facing forwards with your arms extended straight overhead. Lift your left leg up straight out in front of you while bringing your arms down like a karate chop. (Engage your abdominals as you chop!), Your leg should be in between your arms. Bring your leg back down to the floor while raising your arms back overhead. Alternate legs for 15 reps on each side.", 15, 1, goal.LoseWeight, workoutTypes.WeightLoss, difficulty.beginner),
            new exerciseSnippet("Plank Jack", "Begin in a plank position with your hands on the floor, shoulders above your hands and toes tucked under you. Your core should be engaged and your body should be in a straight line from head to toe. Bend your knees slightly and quickly jump your feet out to the side, like you’re doing a jumping jack, but with your palms glued to the floor. Then, quickly jump your feet back together. Repeat for 60 seconds.", 1, 1, goal.LoseWeight, workoutTypes.WeightLoss, difficulty.beginner),
            new exerciseSnippet("Star Jump", "Start standing with your feet together and your knees slightly bent. Your arms should be bent up in front of your chest, like you’re carrying firewood. Next, step your legs out quickly, one leg at a time and shoot your arms out diagonally so you create a star.", 1, 2, goal.LoseWeight, workoutTypes.WeightLoss, difficulty.intermidiate),
            new exerciseSnippet("Fast Feet Touchdown", "Stand with your feet a little wider than hip-width apart. Bend your knees and turn out your feet slightly. Loosely hold your arms bent in front of your chest. Balance your weight on the balls of your feet. Keep your upper body relatively stable and focus on moving your feet as fast as you can. Once you step five times on each foot, quickly bend down, touch the ground, and then rise back up and continue hot-stepping from foot to foot. Repeat for 60 seconds.", 1, 2, goal.LoseWeight, workoutTypes.WeightLoss, difficulty.intermidiate),
            new exerciseSnippet("Single-Leg Skip", "Stand with the right leg behind you in a shallow lunge position. As if you’re about to run a sprint, bend your arms and bring the right arm in front of you, left arm behind you. Push off your back foot and perform a skip on your left leg, bringing your right leg up and driving up with your left arm. Land softly on our left leg and bring your right leg back to the starting sprint position. Perform 10 reps on each side.", 10, 2, goal.LoseWeight, workoutTypes.WeightLoss, difficulty.intermidiate),
            new exerciseSnippet("Overhead Chop", "Start facing forwards with your arms extended straight overhead. Lift your left leg up straight out in front of you while bringing your arms down like a karate chop. (Engage your abdominals as you chop!), Your leg should be in between your arms. Bring your leg back down to the floor while raising your arms back overhead. Alternate legs for 15 reps on each side.", 15, 2, goal.LoseWeight, workoutTypes.WeightLoss, difficulty.intermidiate),
            new exerciseSnippet("Plank Jack", "Begin in a plank position with your hands on the floor, shoulders above your hands and toes tucked under you. Your core should be engaged and your body should be in a straight line from head to toe. Bend your knees slightly and quickly jump your feet out to the side, like you’re doing a jumping jack, but with your palms glued to the floor. Then, quickly jump your feet back together. Repeat for 60 seconds.", 1, 2, goal.LoseWeight, workoutTypes.WeightLoss, difficulty.intermidiate),
            new exerciseSnippet("Star Jump", "Start standing with your feet together and your knees slightly bent. Your arms should be bent up in front of your chest, like you’re carrying firewood. Next, step your legs out quickly, one leg at a time and shoot your arms out diagonally so you create a star.", 1, 3, goal.LoseWeight, workoutTypes.WeightLoss, difficulty.advanced),
            new exerciseSnippet("Fast Feet Touchdown", "Stand with your feet a little wider than hip-width apart. Bend your knees and turn out your feet slightly. Loosely hold your arms bent in front of your chest. Balance your weight on the balls of your feet. Keep your upper body relatively stable and focus on moving your feet as fast as you can. Once you step five times on each foot, quickly bend down, touch the ground, and then rise back up and continue hot-stepping from foot to foot. Repeat for 60 seconds.", 1, 3, goal.LoseWeight, workoutTypes.WeightLoss, difficulty.advanced),
            new exerciseSnippet("Single-Leg Skip", "Stand with the right leg behind you in a shallow lunge position. As if you’re about to run a sprint, bend your arms and bring the right arm in front of you, left arm behind you. Push off your back foot and perform a skip on your left leg, bringing your right leg up and driving up with your left arm. Land softly on our left leg and bring your right leg back to the starting sprint position. Perform 10 reps on each side.", 10, 3, goal.LoseWeight, workoutTypes.WeightLoss, difficulty.advanced),
            new exerciseSnippet("Overhead Chop", "Start facing forwards with your arms extended straight overhead. Lift your left leg up straight out in front of you while bringing your arms down like a karate chop. (Engage your abdominals as you chop!), Your leg should be in between your arms. Bring your leg back down to the floor while raising your arms back overhead. Alternate legs for 15 reps on each side.", 15, 3, goal.LoseWeight, workoutTypes.WeightLoss, difficulty.advanced),
            new exerciseSnippet("Plank Jack", "Begin in a plank position with your hands on the floor, shoulders above your hands and toes tucked under you. Your core should be engaged and your body should be in a straight line from head to toe. Bend your knees slightly and quickly jump your feet out to the side, like you’re doing a jumping jack, but with your palms glued to the floor. Then, quickly jump your feet back together. Repeat for 60 seconds.", 1, 3, goal.LoseWeight, workoutTypes.WeightLoss, difficulty.advanced),
            new exerciseSnippet("Sprints", "Sprints outside, on a treadmill, or even up stairs or bleachers are great to burn the most calories in the least amount of time. No equipment is really necessary and you can do these workouts just about anywhere.", 1, 1, goal.LoseWeight, workoutTypes.Cardio, difficulty.all),
            new exerciseSnippet("Rowing", "Rowing is a great way to incorporate the upper and lower body in a relatively low-stress manner on your joints and ligaments. It’s also a great way to work the posterior chain. Following a moderate pace on the rowing machine can burn upwards of 800 calories per hour for an 180-lb guy, but increasing the intensity with short sprints will get that number well over 1,000 calories per hour very quickly.", 1, 1, goal.LoseWeight, workoutTypes.Cardio, difficulty.all),
            new exerciseSnippet("Swimming", "Swimming is a total-body workout that starts the second you begin treading water. You’re essentially fighting gravity, so your muscles are working extra hard to keep you afloat without getting a break until you’re out of the water. In fact, with just one minute of fast swimming, you’ll burn 14 calories.", 1, 1, goal.LoseWeight, workoutTypes.Cardio, difficulty.all),
            new exerciseSnippet("Cycling", "Stationary bikes are a mainstay at most gyms, but there’s a reason most people aren’t waiting in line to use them: You must be willing to go at an intense rate—so no pedaling while scrolling through your smartphone. During a vigorous indoor cycling or spin class, the average 180-lb. man may burn close to 1,150 calories per hour, while a more moderate ride will only burn half that amount at about 675 calories per hour.", 1, 1, goal.LoseWeight, workoutTypes.Cardio, difficulty.all),
            new exerciseSnippet("Jumping Rope", "Jumping rope not only enhances your footwork, shoulder strength, and coordination, but also simulates sprinting, allowing you to burn as much as 500 calories in just 30 minutes.", 1, 1, goal.LoseWeight, workoutTypes.Cardio, difficulty.all),
            new exerciseSnippet("Stair Climber (Or Climbing Stairs),", "A stair climber offers another popular way to burn fat and calories, but only about 500-600 calories for an 180-lb. man at a moderate pace. Because of the higher leg lift involved, climbing stairs uses significantly more muscles than just walking—strengthening your legs in a functional way. The primary drawback: Stair climbers can put a lot of weight and pressure on your joints, so it can be difficult for people with bad knees. If you don’t have access to a Stair Climber, just use the stairs in your house.", 1, 1, goal.LoseWeight, workoutTypes.Cardio, difficulty.all),
            new exerciseSnippet("Running (Moderate Pace),", "Running at a steady, moderate pace is a sure way to burn fat and calories, but it’s not the most economical way to build or even maintain muscle.", 1, 1, goal.LoseWeight, workoutTypes.Cardio, difficulty.all),
            new exerciseSnippet("Mobility", "One of the best things you can do on an off day is to work on your flexibility and mobility. After all, what good is strength if we can’t move our body properly to utilize it! Dynamic stretching and mobility work helps prepare our body for the rigors of strength training and keeps us injury free!", 1, 1, goal.all, workoutTypes.ActiveRecovery, difficulty.all),
            new exerciseSnippet("Fun Activities", "Exercise does not need to be exhausting or miserable. If you haven’t found an activity you enjoy yet, you haven’t tried enough new things. The point is to get outside, remember it’s a good day to be alive, and that we are built to move.", 1, 1, goal.all, workoutTypes.ActiveRecovery, difficulty.all),
            new exerciseSnippet("Intervals", "In interval training, you’ll be varying your running pace. This means you may switch between jogging and walking, or walking and sprinting (there are few different methods of interval training),. This training style can help speed up your metabolism for the hours after you finish.", 1, 1, goal.all, workoutTypes.ActiveRecovery, difficulty.all),
            new exerciseSnippet("Sprinting", "If you like the idea of burning extra calories and building explosive power and speed, check out our article on becoming the Flash. Find a hill, sprint up it, walk down, and repeat the process for 10-20 minutes. No need to overthink it!", 1, 1, goal.all, workoutTypes.ActiveRecovery, difficulty.all),
            new exerciseSnippet("Long Walks", "Walking is a low-impact activity that burns extra calories and doesn’t overly tax your body. What a long walk will be is different for everybody based on their level of fitness, but walking is one of the best things you can do for yourself!", 1, 1, goal.all, workoutTypes.ActiveRecovery, difficulty.all),
            new exerciseSnippet("Yoga", "Yoga lengthens our muscles and tendons, aids in their recovery, and helps our body develop better mobility and flexibility. It’s the perfect way to create a strong AND mobile body, ready for anything and everything we throw at it.", 1, 1, goal.all, workoutTypes.ActiveRecovery, difficulty.all),
            new exerciseSnippet("Foam Roller", "The important thing for today’s lesson: a rolling massage has been shown to help alleviate muscle soreness. Which means it’s a perfect inclusion for active recovery.", 1, 1, goal.all, workoutTypes.ActiveRecovery, difficulty.all),
            new exerciseSnippet("Knee Push-Up", "Start at the top of the push-up position with your hands on the floor, arms straight and underneath your shoulders. Step your knees back behind you so that there is a straight line through your body from your knees up to your head. Engage your glutes, tense your legs and brace your core to keep your body rigid.", 10, 2, goal.GainWeightMuscle, workoutTypes.StrengthTraining, difficulty.beginner),
            new exerciseSnippet("Assisted Bodyweight Squat (If you can’t do regular bodyweight squats),", "Start the movement as if you were about to sit down, pushing your hips down and back. Descend as far as you can without excessive rounding of the back and without the knees caving inwards. Use the support to ensure you hold proper posture throughout the entire movement. Attempt to spread the floor with your feet as you rise back up to the start position.", 10, 2, goal.GainWeightMuscle, workoutTypes.StrengthTraining, difficulty.beginner),
            new exerciseSnippet("Supported Lunges (If you can’t do regular lunges),", "Shift weight into the front leg and step the opposite leg back into a comfortable low lunge, without disturbing spinal curves or leaning forward. Slowly lower back knee to the floor, transitioning onto the top of the back foot, maintaining grip on device and placing as much weight as needed into hands.", 10, 2, goal.GainWeightMuscle, workoutTypes.StrengthTraining, difficulty.beginner),
            new exerciseSnippet("One Arm Row", "If you don’t have a dumbbell, use a milk jug, suitcase, or similar item. Bring the dumbbell up to your chest, concentrating on lifting it with your back and shoulder muscles rather than your arms. Keep your chest still as you lift. At the top of the movement, squeeze your shoulder and back muscles. Lower the dumbbell slowly until your arm is fully extended again. Do all your reps on one arm before switching to the other side.", 10, 2, goal.GainWeightMuscle, workoutTypes.StrengthTraining, difficulty.beginner),
            new exerciseSnippet("Plank", "Plant hands directly under shoulders (slightly wider than shoulder-width), like you’re about to do a push-up. Ground toes into the floor and squeeze glutes to stabilize your body. Your legs should be working, too — be careful not to lock or hyperextend your knees. Neutralize your neck and spine by looking at a spot on the floor about a foot beyond your hands. Your head should be in line with your back. Hold for 30 seconds before repeating.", 1, 2, goal.GainWeightMuscle, workoutTypes.StrengthTraining, difficulty.beginner),
            new exerciseSnippet("Side Plank", "Lie on your side with your knees bent, and prop your upper body up on your elbow. Raise your hips off the floor, and hold for 6 seconds. Rest for 10 seconds. Repeat.", 3, 2, goal.GainWeightMuscle, workoutTypes.StrengthTraining, difficulty.beginner),
            new exerciseSnippet("Walking Jack (If you can’t do jumping jacks),", "Begin this exercise by standing tgoal.all, holding your chest high, and engaging your core for balance and strength. Start by stepping out wide to the side with your right foot. ... This walking jack is a great way to warm up for any other exercises and also a great foundation to build into actually jumping up and down. Lasts 60 secs.", 1, 2, goal.GainWeightMuscle, workoutTypes.StrengthTraining, difficulty.beginner),
            new exerciseSnippet("Regular Push-Up", "Exercise done laying with face, palms and toes facing down, keeping legs and back straight, extending arms straight to push body up and back down again. ", 10, 3, goal.GainWeightMuscle, workoutTypes.StrengthTraining, difficulty.intermidiate),
            new exerciseSnippet("Bodyweight Squat", "Set your feet shoulder-width apart, toes slightly turned out. Slowly bend at the knees and drop your hips to lower your body. At the bottom of the exercise pause for a moment and strongly push back up to the starting position, mirroring the descent.", 10, 3, goal.GainWeightMuscle, workoutTypes.StrengthTraining, difficulty.intermidiate),
            new exerciseSnippet("Lunges", "Stand tall with feet hip-width apart. Engage your core. Take a big step forward with your right leg. Start to shift your weight forward so the heel hits the floor first. Lower your body until the right thigh is parallel to the floor and the right shin is vertical. It’s OK if the knee shifts forward a little as long as it doesn’t go past the right toe. If mobility allows, lightly tap the left knee to the floor while keeping weight in the right heel. Press into right heel to drive back up to starting position.", 10, 3, goal.GainWeightMuscle, workoutTypes.StrengthTraining, difficulty.intermidiate),
            new exerciseSnippet("One Arm Row", "If you don’t have a dumbbell, use a milk jug, suitcase, or similar item. Bring the dumbbell up to your chest, concentrating on lifting it with your back and shoulder muscles rather than your arms. Keep your chest still as you lift. At the top of the movement, squeeze your shoulder and back muscles. Lower the dumbbell slowly until your arm is fully extended again. Do all your reps on one arm before switching to the other side.", 10, 3, goal.GainWeightMuscle, workoutTypes.StrengthTraining, difficulty.intermidiate),
            new exerciseSnippet("Plank", "Plant hands directly under shoulders (slightly wider than shoulder-width), like you’re about to do a push-up. Ground toes into the floor and squeeze glutes to stabilize your body. Your legs should be working, too — be careful not to lock or hyperextend your knees. Neutralize your neck and spine by looking at a spot on the floor about a foot beyond your hands. Your head should be in line with your back. Hold for 45 seconds before repeating.", 1, 2, goal.GainWeightMuscle, workoutTypes.StrengthTraining, difficulty.intermidiate),
            new exerciseSnippet("Side Plank", "Lie on your side with your knees bent, and prop your upper body up on your elbow. Raise your hips off the floor, and hold for 6 seconds. Rest for 10 seconds. Repeat.", 4, 2, goal.GainWeightMuscle, workoutTypes.StrengthTraining, difficulty.intermidiate),
            new exerciseSnippet("Jumping Jacks", "Performed by jumping to a position with the legs spread wide and the hands going overhead, sometimes in a clap, and then returning to a position with the feet together and the arms at the sides. Lasts 60 secs.", 1, 3, goal.GainWeightMuscle, workoutTypes.StrengthTraining, difficulty.intermidiate),
            new exerciseSnippet("Elevated Push-Up", "Place your hands on an elevated surface—such a box or bench—with your arms straight and your hands directly below your shoulders. Walk your legs out behind you until you're in a pushup position. ... Lower your body until your chest nearly touches the box of bench.", 10, 4, goal.GainWeightMuscle, workoutTypes.StrengthTraining, difficulty.advanced),
            new exerciseSnippet("Bodyweight Squat", "Set your feet shoulder-width apart, toes slightly turned out. Slowly bend at the knees and drop your hips to lower your body. At the bottom of the exercise pause for a moment and strongly push back up to the starting position, mirroring the descent.", 10, 4, goal.GainWeightMuscle, workoutTypes.StrengthTraining, difficulty.advanced),
            new exerciseSnippet("Lunges", "Stand tall with feet hip-width apart. Engage your core. Take a big step forward with your right leg. Start to shift your weight forward so the heel hits the floor first. Lower your body until the right thigh is parallel to the floor and the right shin is vertical. It’s OK if the knee shifts forward a little as long as it doesn’t go past the right toe. If mobility allows, lightly tap the left knee to the floor while keeping weight in the right heel. Press into right heel to drive back up to starting position.", 10, 4, goal.GainWeightMuscle, workoutTypes.StrengthTraining, difficulty.advanced),
            new exerciseSnippet("One Arm Row", "If you don’t have a dumbbell, use a milk jug, suitcase, or similar item. Bring the dumbbell up to your chest, concentrating on lifting it with your back and shoulder muscles rather than your arms. Keep your chest still as you lift. At the top of the movement, squeeze your shoulder and back muscles. Lower the dumbbell slowly until your arm is fully extended again. Do all your reps on one arm before switching to the other side.", 10, 4, goal.GainWeightMuscle, workoutTypes.StrengthTraining, difficulty.advanced),
            new exerciseSnippet("Plank", "Plant hands directly under shoulders (slightly wider than shoulder-width), like you’re about to do a push-up. Ground toes into the floor and squeeze glutes to stabilize your body. Your legs should be working, too — be careful not to lock or hyperextend your knees. Neutralize your neck and spine by looking at a spot on the floor about a foot beyond your hands. Your head should be in line with your back. Hold for 60 seconds before repeating.", 1, 2, goal.GainWeightMuscle, workoutTypes.StrengthTraining, difficulty.advanced),
            new exerciseSnippet("Side Plank", "Lie on your side with your knees bent, and prop your upper body up on your elbow. Raise your hips off the floor, and hold for 6 seconds. Rest for 10 seconds. Repeat.", 5, 2, goal.GainWeightMuscle, workoutTypes.StrengthTraining, difficulty.advanced),
            new exerciseSnippet("Jumping Jacks", "Performed by jumping to a position with the legs spread wide and the hands going overhead, sometimes in a clap, and then returning to a position with the feet together and the arms at the sides. Lasts 60 secs.", 1, 4, goal.GainWeightMuscle, workoutTypes.StrengthTraining, difficulty.advanced),            new exerciseSnippet("Jump Rope", "60 sec", 1, 1, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.beginner),
            new exerciseSnippet("Plank", "60 sec", 1, 1, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.beginner),
            new exerciseSnippet("Oblique Crunch", "Stand with your feet shoulder-distance apart. Fold the jump rope in half twice so it’s shoulder-distance apart when you hold each end and lift it up overhead. Pull each end of the rope to create resistance in your arms. Engaging your core, crunch to your left side, while dynamically pressing the rope up overhead. Both sides count as one rep.", 8, 1, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.beginner),
            new exerciseSnippet("Single Leg Forward Hinge", "Stand with your feet together. Lift your left leg up so your left knee is bent. Fold your jump rope in half and hold each end of the rope with your hands, pulling it tightly. Balancing your weight on your right leg, hinge your torso forward and bring the jump rope over your left knee to touch your shin. Bring the jump rope back overhead. Do eight reps for both legs..", 8, 1, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.beginner),
            new exerciseSnippet("In and Out Jumps", "Stand over the jump rope with your feet a little wider than hip-distance apart. When you take your next jump, land with your feet together. Take another jump and bring your feet back out so they’re a little wider than hip distance. This is one rep. Repeat for seven more reps.", 8, 1, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.beginner),
            new exerciseSnippet("Scissor Jumps", "Stand over the jump rope with your feet together. When you take your next jump, scissor your feet, stepping with one foot forward and the other back. This is one rep. Repeat for seven more reps.", 8, 1, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.beginner),
            new exerciseSnippet("Single-Leg Hops", "Stand over the jump rope with your feet together. Raise your right foot off the ground and bend your right knee. Balance your weight on your left leg. When you jump over the rope, turn it over your left foot and land on the ball of your foot. Repeat for seven more reps before switching sides.", 8, 1, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.beginner),
            new exerciseSnippet("Shoulder Fly", "Stand on top of the jump rope with your feet shoulder-width apart. Hold onto each handle tightly with your hands close together in front of you. Engaging your arms and your scapula, bring your arms out into a T and pinch your shoulder blades together. Imagine that there’s something in between your shoulder blades and squeeze in tightly.", 8, 1, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.beginner),
            new exerciseSnippet("Upright Row", "Stand on top of the jump rope with your feet shoulder-width apart. Hold onto each handle tightly with your arms straight out in front of you. Using your biceps, pull the handles to your sides as you flex your elbows. You should feel the retraction in your shoulder blades and engage your traps and lats.", 8, 1, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.beginner),
            new exerciseSnippet("Tricep Fly", "Stand with your feet about hip-distance apart with a slight bend in your knees. Fold your jump rope twice and hold onto each end behind you, palms facing away from you. Pull rope taut to create resistance. Keeping arms straight, pulse your arms up and back down, engaging your triceps.", 8, 1, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.beginner),
            new exerciseSnippet("Stationary Lunges", " Place your jump rope on the floor. Standing with your feet hip-distance apart, step your right foot over the jump rope. Lower until both knees form 90-degree angles and your left knee hovers just above the ground. Rise back up and repeat.", 8, 1, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.beginner),
            new exerciseSnippet("Agility Hops", "Place your jump rope on the floor. Standing with your feet together and hands on your hips, hop forward and back over the rope. Staying light on the balls of your feet, you’re aiming for quickness on this one.", 8, 1, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.beginner),
            new exerciseSnippet("Basic Jump Rope", "Choose a four-to-five minute song, and get those feet jumping. Aim to match the beat of the song, and don’t let up.", 1, 1, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.beginner),
            new exerciseSnippet("Sprint", "Stand over the rope with your feet together. Do basic jumps at a moderate speed for 20 seconds. As you approach 20 seconds, speed up your pace before you start jumping as fast as you can for another 20 seconds.", 1, 1, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.beginner),
            new exerciseSnippet("Jump Rope", "60 sec", 1, 2, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.intermidiate),
            new exerciseSnippet("Plank", "60 sec", 1, 2, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.intermidiate),
            new exerciseSnippet("Oblique Crunch", "Stand with your feet shoulder-distance apart. Fold the jump rope in half twice so it’s shoulder-distance apart when you hold each end and lift it up overhead. Pull each end of the rope to create resistance in your arms. Engaging your core, crunch to your left side, while dynamically pressing the rope up overhead. Both sides count as one rep.", 8, 2, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.intermidiate),
            new exerciseSnippet("Single Leg Forward Hinge", "Stand with your feet together. Lift your left leg up so your left knee is bent. Fold your jump rope in half and hold each end of the rope with your hands, pulling it tightly. Balancing your weight on your right leg, hinge your torso forward and bring the jump rope over your left knee to touch your shin. Bring the jump rope back overhead. Do eight reps for both legs..", 8, 2, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.intermidiate),
            new exerciseSnippet("In and Out Jumps", "Stand over the jump rope with your feet a little wider than hip-distance apart. When you take your next jump, land with your feet together. Take another jump and bring your feet back out so they’re a little wider than hip distance. This is one rep. Repeat for seven more reps.", 8, 2, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.intermidiate),
            new exerciseSnippet("Scissor Jumps", "Stand over the jump rope with your feet together. When you take your next jump, scissor your feet, stepping with one foot forward and the other back. This is one rep. Repeat for seven more reps.", 8, 2, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.intermidiate),
            new exerciseSnippet("Single-Leg Hops", "Stand over the jump rope with your feet together. Raise your right foot off the ground and bend your right knee. Balance your weight on your left leg. When you jump over the rope, turn it over your left foot and land on the ball of your foot. Repeat for seven more reps before switching sides.", 8, 2, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.intermidiate),
            new exerciseSnippet("Shoulder Fly", "Stand on top of the jump rope with your feet shoulder-width apart. Hold onto each handle tightly with your hands close together in front of you. Engaging your arms and your scapula, bring your arms out into a T and pinch your shoulder blades together. Imagine that there’s something in between your shoulder blades and squeeze in tightly.", 8, 2, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.intermidiate),
            new exerciseSnippet("Upright Row", "Stand on top of the jump rope with your feet shoulder-width apart. Hold onto each handle tightly with your arms straight out in front of you. Using your biceps, pull the handles to your sides as you flex your elbows. You should feel the retraction in your shoulder blades and engage your traps and lats.", 8, 2, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.intermidiate),
            new exerciseSnippet("Tricep Fly", "Stand with your feet about hip-distance apart with a slight bend in your knees. Fold your jump rope twice and hold onto each end behind you, palms facing away from you. Pull rope taut to create resistance. Keeping arms straight, pulse your arms up and back down, engaging your triceps.", 8, 2, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.intermidiate),
            new exerciseSnippet("Stationary Lunges", " Place your jump rope on the floor. Standing with your feet hip-distance apart, step your right foot over the jump rope. Lower until both knees form 90-degree angles and your left knee hovers just above the ground. Rise back up and repeat.", 8, 2, goal.GainWeightMuscle, workoutTypes.HIIT,difficulty.intermidiate),
            new exerciseSnippet("Agility Hops", "Place your jump rope on the floor. Standing with your feet together and hands on your hips, hop forward and back over the rope. Staying light on the balls of your feet, you’re aiming for quickness on this one.", 8, 2, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.intermidiate),
            new exerciseSnippet("Basic Jump Rope", "Choose a four-to-five minute song, and get those feet jumping. Aim to match the beat of the song, and don’t let up.", 1, 2, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.intermidiate),
            new exerciseSnippet("Sprint", "Stand over the rope with your feet together. Do basic jumps at a moderate speed for 20 seconds. As you approach 20 seconds, speed up your pace before you start jumping as fast as you can for another 20 seconds.", 1, 2, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.intermidiate),
            new exerciseSnippet("Jump Rope", "60 sec", 1, 3, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.advanced),
            new exerciseSnippet("Plank", "60 sec", 1, 3, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.advanced),
            new exerciseSnippet("Oblique Crunch", "Stand with your feet shoulder-distance apart. Fold the jump rope in half twice so it’s shoulder-distance apart when you hold each end and lift it up overhead. Pull each end of the rope to create resistance in your arms. Engaging your core, crunch to your left side, while dynamically pressing the rope up overhead. Both sides count as one rep.", 8, 3, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.advanced),
            new exerciseSnippet("Single Leg Forward Hinge", "Stand with your feet together. Lift your left leg up so your left knee is bent. Fold your jump rope in half and hold each end of the rope with your hands, pulling it tightly. Balancing your weight on your right leg, hinge your torso forward and bring the jump rope over your left knee to touch your shin. Bring the jump rope back overhead. Do eight reps for both legs..", 8, 3, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.advanced),
            new exerciseSnippet("In and Out Jumps", "Stand over the jump rope with your feet a little wider than hip-distance apart. When you take your next jump, land with your feet together. Take another jump and bring your feet back out so they’re a little wider than hip distance. This is one rep. Repeat for seven more reps.", 8, 3, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.advanced),
            new exerciseSnippet("Scissor Jumps", "Stand over the jump rope with your feet together. When you take your next jump, scissor your feet, stepping with one foot forward and the other back. This is one rep. Repeat for seven more reps.", 8, 3, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.advanced),
            new exerciseSnippet("Single-Leg Hops", "Stand over the jump rope with your feet together. Raise your right foot off the ground and bend your right knee. Balance your weight on your left leg. When you jump over the rope, turn it over your left foot and land on the ball of your foot. Repeat for seven more reps before switching sides.", 8, 3, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.advanced),
            new exerciseSnippet("Shoulder Fly", "Stand on top of the jump rope with your feet shoulder-width apart. Hold onto each handle tightly with your hands close together in front of you. Engaging your arms and your scapula, bring your arms out into a T and pinch your shoulder blades together. Imagine that there’s something in between your shoulder blades and squeeze in tightly.", 8, 3, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.advanced),
            new exerciseSnippet("Upright Row", "Stand on top of the jump rope with your feet shoulder-width apart. Hold onto each handle tightly with your arms straight out in front of you. Using your biceps, pull the handles to your sides as you flex your elbows. You should feel the retraction in your shoulder blades and engage your traps and lats.", 8, 3, goal.GainWeightMuscle, workoutTypes.HIIT,difficulty.advanced),
            new exerciseSnippet("Tricep Fly", "Stand with your feet about hip-distance apart with a slight bend in your knees. Fold your jump rope twice and hold onto each end behind you, palms facing away from you. Pull rope taut to create resistance. Keeping arms straight, pulse your arms up and back down, engaging your triceps.", 8, 3, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.advanced),
            new exerciseSnippet("Stationary Lunges", " Place your jump rope on the floor. Standing with your feet hip-distance apart, step your right foot over the jump rope. Lower until both knees form 90-degree angles and your left knee hovers just above the ground. Rise back up and repeat.", 8, 3, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.advanced),
            new exerciseSnippet("Agility Hops", "Place your jump rope on the floor. Standing with your feet together and hands on your hips, hop forward and back over the rope. Staying light on the balls of your feet, you’re aiming for quickness on this one.", 8, 3, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.advanced),
            new exerciseSnippet("Basic Jump Rope", "Choose a four-to-five minute song, and get those feet jumping. Aim to match the beat of the song, and don’t let up.", 1, 3, goal.GainWeightMuscle, workoutTypes.HIIT, difficulty.advanced),
            new exerciseSnippet("Sprint", "Stand over the rope with your feet together. Do basic jumps at a moderate speed for 20 seconds. As you approach 20 seconds, speed up your pace before you start jumping as fast as you can for another 20 seconds.", 1, 3, goal.GainWeightMuscle, workoutTypes.HIIT,difficulty.advanced),
            new exerciseSnippet("Mobility", "One of the best things you can do on an off day is to work on your flexibility and mobility. After goal.all, what good is strength if we can’t move our body properly to utilize it! Dynamic stretching and mobility work helps prepare our body for the rigors of strength training and keeps us injury free!", 1, 1, goal.all, workoutTypes.ActiveRecovery, difficulty.all),
            new exerciseSnippet("Fun Activities", "Exercise does not need to be exhausting or miserable. If you haven’t found an activity you enjoy yet, you haven’t tried enough new things. The point is to get outside, remember it’s a good day to be alive, and that we are built to move.", 1, 1, goal.all, workoutTypes.ActiveRecovery, difficulty.all),
            new exerciseSnippet("Intervals", "In interval training, you’ll be varying your running pace. This means you may switch between jogging and walking, or walking and sprinting (there are few different methods of interval training),. This training style can help speed up your metabolism for the hours after you finish.", 1, 1, goal.all, workoutTypes.ActiveRecovery, difficulty.all),
            new exerciseSnippet("Sprinting", "If you like the idea of burning extra calories and building explosive power and speed, check out our article on becoming the Flash. Find a hill, sprint up it, walk down, and repeat the process for 10-20 minutes. No need to overthink it!", 1, 1, goal.all, workoutTypes.ActiveRecovery, difficulty.all),
            new exerciseSnippet("Long Walks", "Walking is a low-impact activity that burns extra calories and doesn’t overly tax your body. What a long walk will be is different for everybody based on their level of fitness, but walking is one of the best things you can do for yourself!", 1, 1, goal.all, workoutTypes.ActiveRecovery, difficulty.all),
            new exerciseSnippet("Yoga", "Yoga lengthens our muscles and tendons, aids in their recovery, and helps our body develop better mobility and flexibility. It’s the perfect way to create a strong AND mobile body, ready for anything and everything we throw at it.", 1, 1, goal.all, workoutTypes.ActiveRecovery, difficulty.all),
            new exerciseSnippet("Foam Roller", "The important thing for today’s lesson: a rolling massage has been shown to help alleviate muscle soreness. Which means it’s a perfect inclusion for active recovery.", 1, 1, goal.all, workoutTypes.ActiveRecovery, difficulty.all),
            new exerciseSnippet("Bent-Over Press Against Wall", "Start in a low lunge position. Place hands on the wall at about chest level. Lean into the wall and push. The farther down you bend, the more the exercise will target your shoulders. The more you stay upright, the more the exercise will target your chest. Make sure to use 80-90% force for all exercises and to contract for 10 sec each rep. Use 45-60 sec rests between sets.", 2, 1, goal.MaintainWeightTone, workoutTypes.Isometric, difficulty.beginner),
            new exerciseSnippet("Prayer Pose", "Place palms together. Your elbows can be flaring out or pointed toward the ground. Press your hands together. The tighter you press, the harder it will be. Make sure to use 80-90% force for all exercises and to contract for 10 sec each rep. Use 45-60 sec rests between sets.", 2, 1, goal.MaintainWeightTone, workoutTypes.Isometric, difficulty.beginner),
            new exerciseSnippet("High Plank", "Get into push-up position, making sure your spine is in a straight line. Press the floor away from you, broadening across your chest. Engage your core and breathe deeply. Make sure to use 80-90% force for all exercises and to contract for 10 sec each rep. Use 45-60 sec rests between sets.", 2, 1, goal.MaintainWeightTone, workoutTypes.Isometric, difficulty.beginner),
            new exerciseSnippet("Self-Arm Wrestling", "Bend your right arm at a 90-degree angle. Grab your right hand with your left hand. Push them together as hard as you can. While your right biceps prevents your arm from dropping, your left triceps is trying to push your right arm down. Repeat on the other side. Make sure to use 80-90% force for all exercises and to contract for 10 sec each rep. Use 45-60 sec rests between sets.", 2, 1, goal.MaintainWeightTone, workoutTypes.Isometric, difficulty.beginner),
            new exerciseSnippet("Tricep Extension Against Wall", "Get into a lunge position with your fists on the wall at head level. Use your triceps to push your fists into the wall. Make sure to use 80-90% force for all exercises and to contract for 10 sec each rep. Use 45-60 sec rests between sets.", 2, 1, goal.MaintainWeightTone, workoutTypes.Isometric, difficulty.beginner),
            new exerciseSnippet("Forearm Plank", "Get into a forearm plank position. Keep spine in a straight line and tighten abs as much as you can. Normally, people try to just hold this position, but contracting your abs will provide even more benefit for your core. Make sure to use 80-90% force for all exercises and to contract for 10 sec each rep. Use 45-60 sec rests between sets.", 2, 1, goal.MaintainWeightTone, workoutTypes.Isometric, difficulty.beginner),
            new exerciseSnippet("Low Squat", "Stand with your feet about shoulder-width apart. Squat so thighs are parallel to the floor. Instead of just holding this position, try to squeeze your feet together. This will force your inner thigh muscles to contract even more. Make sure to use 80-90% force for all exercises and to contract for 10 sec each rep. Use 45-60 sec rests between sets.", 2, 1, goal.MaintainWeightTone, workoutTypes.Isometric, difficulty.beginner),
            new exerciseSnippet("Bent-Over Press Against Wall", "Start in a low lunge position. Place hands on the wall at about chest level. Lean into the wall and push. The farther down you bend, the more the exercise will target your shoulders. The more you stay upright, the more the exercise will target your chest. Make sure to use 80-90% force for all exercises and to contract for 10 sec each rep. Use 45-60 sec rests between sets.", 3, 1, goal.MaintainWeightTone, workoutTypes.Isometric, difficulty.intermidiate),
            new exerciseSnippet("Prayer Pose", "Place palms together. Your elbows can be flaring out or pointed toward the ground. Press your hands together. The tighter you press, the harder it will be. Make sure to use 80-90% force for all exercises and to contract for 10 sec each rep. Use 45-60 sec rests between sets.", 3, 1, goal.MaintainWeightTone, workoutTypes.Isometric, difficulty.intermidiate),
            new exerciseSnippet("High Plank", "Get into push-up position, making sure your spine is in a straight line. Press the floor away from you, broadening across your chest. Engage your core and breathe deeply. Make sure to use 80-90% force for all exercises and to contract for 10 sec each rep. Use 45-60 sec rests between sets.", 3, 1, goal.MaintainWeightTone, workoutTypes.Isometric, difficulty.intermidiate),
            new exerciseSnippet("Self-Arm Wrestling", "Bend your right arm at a 90-degree angle. Grab your right hand with your left hand. Push them together as hard as you can. While your right biceps prevents your arm from dropping, your left triceps is trying to push your right arm down. Repeat on the other side. Make sure to use 80-90% force for all exercises and to contract for 10 sec each rep. Use 45-60 sec rests between sets.", 3, 1, goal.MaintainWeightTone, workoutTypes.Isometric, difficulty.intermidiate),
            new exerciseSnippet("Tricep Extension Against Wall", "Get into a lunge position with your fists on the wall at head level. Use your triceps to push your fists into the wall. Make sure to use 80-90% force for all exercises and to contract for 10 sec each rep. Use 45-60 sec rests between sets.", 3, 1, goal.MaintainWeightTone, workoutTypes.Isometric, difficulty.intermidiate),
            new exerciseSnippet("Forearm Plank", "Get into a forearm plank position. Keep spine in a straight line and tighten abs as much as you can. Normally, people try to just hold this position, but contracting your abs will provide even more benefit for your core. Make sure to use 80-90% force for all exercises and to contract for 10 sec each rep. Use 45-60 sec rests between sets.", 3, 1, goal.MaintainWeightTone, workoutTypes.Isometric, difficulty.intermidiate),
            new exerciseSnippet("Low Squat", "Stand with your feet about shoulder-width apart. Squat so thighs are parallel to the floor. Instead of just holding this position, try to squeeze your feet together. This will force your inner thigh muscles to contract even more. Make sure to use 80-90% force for all exercises and to contract for 10 sec each rep. Use 45-60 sec rests between sets.", 3, 1, goal.MaintainWeightTone, workoutTypes.Isometric, difficulty.intermidiate),
            new exerciseSnippet("Bent-Over Press Against Wall", "Start in a low lunge position. Place hands on the wall at about chest level. Lean into the wall and push. The farther down you bend, the more the exercise will target your shoulders. The more you stay upright, the more the exercise will target your chest. Make sure to use 80-90% force for all exercises and to contract for 10 sec each rep. Use 45-60 sec rests between sets.", 4, 1, goal.MaintainWeightTone, workoutTypes.Isometric, difficulty.advanced),
            new exerciseSnippet("Prayer Pose", "Place palms together. Your elbows can be flaring out or pointed toward the ground. Press your hands together. The tighter you press, the harder it will be. Make sure to use 80-90% force for all exercises and to contract for 10 sec each rep. Use 45-60 sec rests between sets.", 4, 1, goal.MaintainWeightTone, workoutTypes.Isometric, difficulty.advanced),
            new exerciseSnippet("High Plank", "Get into push-up position, making sure your spine is in a straight line. Press the floor away from you, broadening across your chest. Engage your core and breathe deeply. Make sure to use 80-90% force for all exercises and to contract for 10 sec each rep. Use 45-60 sec rests between sets.", 4, 1, goal.MaintainWeightTone, workoutTypes.Isometric, difficulty.advanced),
            new exerciseSnippet("Self-Arm Wrestling", "Bend your right arm at a 90-degree angle. Grab your right hand with your left hand. Push them together as hard as you can. While your right biceps prevents your arm from dropping, your left triceps is trying to push your right arm down. Repeat on the other side. Make sure to use 80-90% force for all exercises and to contract for 10 sec each rep. Use 45-60 sec rests between sets.", 4, 1, goal.MaintainWeightTone, workoutTypes.Isometric, difficulty.advanced),
            new exerciseSnippet("Tricep Extension Against Wall", "Get into a lunge position with your fists on the wall at head level. Use your triceps to push your fists into the wall. Make sure to use 80-90% force for all exercises and to contract for 10 sec each rep. Use 45-60 sec rests between sets.", 4, 1, goal.MaintainWeightTone, workoutTypes.Isometric, difficulty.advanced),
            new exerciseSnippet("Forearm Plank", "Get into a forearm plank position. Keep spine in a straight line and tighten abs as much as you can. Normally, people try to just hold this position, but contracting your abs will provide even more benefit for your core. Make sure to use 80-90% force for all exercises and to contract for 10 sec each rep. Use 45-60 sec rests between sets.", 4, 1, goal.MaintainWeightTone, workoutTypes.Isometric, difficulty.advanced),
            new exerciseSnippet("Low Squat", "Stand with your feet about shoulder-width apart. Squat so thighs are parallel to the floor. Instead of just holding this position, try to squeeze your feet together. This will force your inner thigh muscles to contract even more. Make sure to use 80-90% force for all exercises and to contract for 10 sec each rep. Use 45-60 sec rests between sets.", 4, 1, goal.MaintainWeightTone, workoutTypes.Isometric, difficulty.advanced),
            new exerciseSnippet("Plank Squat", "Start with your feet shoulder-width apart and begin to lower the body, keeping your weight in your heels as if you’re sitting back into a chair, until thighs are parallel or close to parallel with the floor. In one fast motion, drop the hands to the floor and jump your feet back to a plank position, making sure the body remains in a straight line from head to toe. Immediately jump your feet back to the squat position to complete one rep.", 3, 10, goal.MaintainWeightTone, workoutTypes.Plyometric, difficulty.beginner),
            new exerciseSnippet("workoutTypes.Plyometric Push-Ups", "Start in a plank position with wrists directly under the shoulders, body in a straight line from head to toe. Lower your chest to the floor and then push up explosively with enough force for your hands to leave the floor for a second, and then land softly.", 3, 10, goal.MaintainWeightTone, workoutTypes.Plyometric, difficulty.beginner),
            new exerciseSnippet("Broad Jumps", "Stand with feet hip-width apart and begin to lower the body, keeping your weight in your heels as if you’re sitting back into a chair, stopping just before your thighs are parallel with the floor. Jump up as high as you can and forward, and focus on landing softly on your feet. Immediately return to the quarter-squat position and repeat.", 3, 10, goal.MaintainWeightTone, workoutTypes.Plyometric, difficulty.beginner),
            new exerciseSnippet("X-Overs", "Stand with feet shoulder-width apart and begin to lower your body, keeping your weight in your heels as if you’re sitting back into a chair until thighs are parallel with the floor. Jump straight up explosively and as your feet leave the floor, cross your right leg in front of your left, then uncross so you land with feet shoulder-width apart to complete one rep. Immediately lower back into the squat and repeat, this time crossing the opposite leg in front.", 3, 10, goal.MaintainWeightTone, workoutTypes.Plyometric, difficulty.beginner),
            new exerciseSnippet("180 Jump Squats", "Stand with feet hip-width apart and begin to lower your body, keeping your weight in your heels as if you’re sitting back into a chair, stopping just before your thighs are parallel with the floor. Jump up, turning your body 180 degrees mid-air, in order to land facing in the opposite direction. Immediately lower into your quarter-squat again, and jump and turn in the opposite direction, so you land in starting position to complete one rep.", 3, 10, goal.MaintainWeightTone, workoutTypes.Plyometric, difficulty.beginner),
            new exerciseSnippet("Pass, Fgoal.all, Go’s", "Kneel on the ground and hold a weighted ball/object with both hands against your chest. Explosively push the ball forward from your chest and release it far as possible. Follow through by falling forward and catching yourself with your hands on the ground shoulder-width apart. Push back up and take off sprinting to the ball. When you get to the bgoal.all, that’s one rep.", 3, 10, goal.MaintainWeightTone, workoutTypes.Plyometric, difficulty.beginner),
            new exerciseSnippet("Plank Squat", "Start with your feet shoulder-width apart and begin to lower the body, keeping your weight in your heels as if you’re sitting back into a chair, until thighs are parallel or close to parallel with the floor. In one fast motion, drop the hands to the floor and jump your feet back to a plank position, making sure the body remains in a straight line from head to toe. Immediately jump your feet back to the squat position to complete one rep.", 4, 10, goal.MaintainWeightTone, workoutTypes.Plyometric, difficulty.intermidiate),
            new exerciseSnippet("workoutTypes.Plyometric Push-Ups", "Start in a plank position with wrists directly under the shoulders, body in a straight line from head to toe. Lower your chest to the floor and then push up explosively with enough force for your hands to leave the floor for a second, and then land softly.", 4, 10, goal.MaintainWeightTone, workoutTypes.Plyometric, difficulty.intermidiate),
            new exerciseSnippet("Broad Jumps", "Stand with feet hip-width apart and begin to lower the body, keeping your weight in your heels as if you’re sitting back into a chair, stopping just before your thighs are parallel with the floor. Jump up as high as you can and forward, and focus on landing softly on your feet. Immediately return to the quarter-squat position and repeat.", 4, 10, goal.MaintainWeightTone, workoutTypes.Plyometric,difficulty.intermidiate),
            new exerciseSnippet("X-Overs", "Stand with feet shoulder-width apart and begin to lower your body, keeping your weight in your heels as if you’re sitting back into a chair until thighs are parallel with the floor. Jump straight up explosively and as your feet leave the floor, cross your right leg in front of your left, then uncross so you land with feet shoulder-width apart to complete one rep. Immediately lower back into the squat and repeat, this time crossing the opposite leg in front.", 4, 10, goal.MaintainWeightTone, workoutTypes.Plyometric, difficulty.intermidiate),
            new exerciseSnippet("180 Jump Squats", "Stand with feet hip-width apart and begin to lower your body, keeping your weight in your heels as if you’re sitting back into a chair, stopping just before your thighs are parallel with the floor. Jump up, turning your body 180 degrees mid-air, in order to land facing in the opposite direction. Immediately lower into your quarter-squat again, and jump and turn in the opposite direction, so you land in starting position to complete one rep.", 4, 10, goal.MaintainWeightTone, workoutTypes.Plyometric, difficulty.intermidiate),
            new exerciseSnippet("Pass, Fgoal.all, Go’s", "Kneel on the ground and hold a weighted ball/object with both hands against your chest. Explosively push the ball forward from your chest and release it far as possible. Follow through by falling forward and catching yourself with your hands on the ground shoulder-width apart. Push back up and take off sprinting to the ball. When you get to the bgoal.all, that’s one rep.", 4, 10, goal.MaintainWeightTone, workoutTypes.Plyometric, difficulty.intermidiate),
            new exerciseSnippet("Plank Squat", "Start with your feet shoulder-width apart and begin to lower the body, keeping your weight in your heels as if you’re sitting back into a chair, until thighs are parallel or close to parallel with the floor. In one fast motion, drop the hands to the floor and jump your feet back to a plank position, making sure the body remains in a straight line from head to toe. Immediately jump your feet back to the squat position to complete one rep.", 5, 10, goal.MaintainWeightTone, workoutTypes.Plyometric, difficulty.advanced),
            new exerciseSnippet("workoutTypes.Plyometric Push-Ups", "Start in a plank position with wrists directly under the shoulders, body in a straight line from head to toe. Lower your chest to the floor and then push up explosively with enough force for your hands to leave the floor for a second, and then land softly.", 5, 10, goal.MaintainWeightTone, workoutTypes.Plyometric, difficulty.advanced),
            new exerciseSnippet("Broad Jumps", "Stand with feet hip-width apart and begin to lower the body, keeping your weight in your heels as if you’re sitting back into a chair, stopping just before your thighs are parallel with the floor. Jump up as high as you can and forward, and focus on landing softly on your feet. Immediately return to the quarter-squat position and repeat.", 5, 10, goal.MaintainWeightTone, workoutTypes.Plyometric, difficulty.advanced),
            new exerciseSnippet("X-Overs", "Stand with feet shoulder-width apart and begin to lower your body, keeping your weight in your heels as if you’re sitting back into a chair until thighs are parallel with the floor. Jump straight up explosively and as your feet leave the floor, cross your right leg in front of your left, then uncross so you land with feet shoulder-width apart to complete one rep. Immediately lower back into the squat and repeat, this time crossing the opposite leg in front.", 5, 10, goal.MaintainWeightTone, workoutTypes.Plyometric, difficulty.advanced),
            new exerciseSnippet("180 Jump Squats", "Stand with feet hip-width apart and begin to lower your body, keeping your weight in your heels as if you’re sitting back into a chair, stopping just before your thighs are parallel with the floor. Jump up, turning your body 180 degrees mid-air, in order to land facing in the opposite direction. Immediately lower into your quarter-squat again, and jump and turn in the opposite direction, so you land in starting position to complete one rep.", 5, 10, goal.MaintainWeightTone, workoutTypes.Plyometric, difficulty.advanced),
            new exerciseSnippet("Pass, Fgoal.all, Go’s", "Kneel on the ground and hold a weighted ball/object with both hands against your chest. Explosively push the ball forward from your chest and release it far as possible. Follow through by falling forward and catching yourself with your hands on the ground shoulder-width apart. Push back up and take off sprinting to the ball. When you get to the bgoal.all, that’s one rep.", 5, 10, goal.MaintainWeightTone, workoutTypes.Plyometric, difficulty.advanced),
            new exerciseSnippet("Mobility", "One of the best things you can do on an off day is to work on your flexibility and mobility. After goal.all, what good is strength if we can’t move our body properly to utilize it! Dynamic stretching and mobility work helps prepare our body for the rigors of strength training and keeps us injury free!", 1, 1, goal.all, workoutTypes.ActiveRecovery, difficulty.all),
            new exerciseSnippet("Fun Activities", "Exercise does not need to be exhausting or miserable. If you haven’t found an activity you enjoy yet, you haven’t tried enough new things. The point is to get outside, remember it’s a good day to be alive, and that we are built to move.", 1, 1, goal.all, workoutTypes.ActiveRecovery, difficulty.all),
            new exerciseSnippet("Intervals", "In interval training, you’ll be varying your running pace. This means you may switch between jogging and walking, or walking and sprinting (there are few different methods of interval training),. This training style can help speed up your metabolism for the hours after you finish.", 1, 1, goal.all, workoutTypes.ActiveRecovery, difficulty.all),
            new exerciseSnippet("Sprinting", "If you like the idea of burning extra calories and building explosive power and speed, check out our article on becoming the Flash. Find a hill, sprint up it, walk down, and repeat the process for 10-20 minutes. No need to overthink it!", 1, 1, goal.all, workoutTypes.ActiveRecovery, difficulty.all),
            new exerciseSnippet("Long Walks", "Walking is a low-impact activity that burns extra calories and doesn’t overly tax your body. What a long walk will be is different for everybody based on their level of fitness, but walking is one of the best things you can do for yourself!", 1, 1, goal.all, workoutTypes.ActiveRecovery, difficulty.all),
            new exerciseSnippet("Yoga", "Yoga lengthens our muscles and tendons, aids in their recovery, and helps our body develop better mobility and flexibility. It’s the perfect way to create a strong AND mobile body, ready for anything and everything we throw at it.", 1, 1, goal.all, workoutTypes.ActiveRecovery, difficulty.all),
            new exerciseSnippet("Foam Roller", "The important thing for today’s lesson: a rolling massage has been shown to help alleviate muscle soreness. Which means it’s a perfect inclusion for active recovery.", 1, 1, goal.all, workoutTypes.ActiveRecovery, difficulty.all),
        };
        public int id { get; set; }
        public List<exerciseSnippet> exercisesInWorkout { get; }
        public Exercise(workoutTypes workoutType, int[] timeRange, int[] amountRange, int exerciseAmount, difficulty difficulty, List<exerciseSnippet> liked, List<exerciseSnippet> disliked)
        {
            for(int i = 0; i < exerciseAmount; i++)
            {
                generateExercise(workoutType, difficulty, timeRange, amountRange, liked, disliked);
            }
        }
        private void generateExercise(workoutTypes workoutType, difficulty difficulty, int[] timeRange, int[] amountRange, List<exerciseSnippet> liked, List<exerciseSnippet> disliked)
        {
            List<exerciseSnippet> filteredDownExercises = exercises.Where(r => r.workoutType == workoutType).ToList();
            exerciseSnippet exerciseSnippet = filteredDownExercises[staticRandom.Instance.Next(0, filteredDownExercises.Count - 1)];
            exerciseSnippet.instructions = exerciseSnippet.instructions.Replace("<time>", staticRandom.Instance.Next(timeRange[0], timeRange[1]).ToString()).Replace("<num>", staticRandom.Instance.Next(amountRange[0], amountRange[1]).ToString());
            if (disliked.Contains(exerciseSnippet))
            {
                exercisesInWorkout.Add(liked[staticRandom.Instance.Next(0, liked.Count - 1)]);
            }
            else
            {
                exercisesInWorkout.Add(exerciseSnippet);
            }
        }
    }
    public enum workoutTypes
    {
        Cardio,
        Aerobic,
        ActiveRecovery,
        StrengthTraining,
        HIIT,
        Isometric,
        Plyometric,
        WeightLoss
    }
    public enum difficulty
    {
        beginner,
        intermidiate,
        advanced,
        all
    }
    public enum goal
    {
        LoseWeight,
        MaintainWeightTone,
        GainWeightMuscle,
        all
    }

}
